import spawn from 'cross-spawn';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(packageRoot, 'src', 'generated');
const codex = process.env.CODEX_EXE ?? 'codex';

function run(args) {
  const result = spawn.sync(codex, args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'inherit'] });
  if (result.error) throw new Error(`Could not run "${codex} ${args.join(' ')}": ${result.error.message}`);
  if (result.status !== 0) throw new Error(`"${codex} ${args.join(' ')}" exited with code ${result.status}`);
  return result.stdout.trim();
}

// ClientRequest.ts and ServerRequest.ts list `"method": "x", id: RequestId, params: FooParams` (`params?:` when optional).
// Codex names the reply type after the params type, so FooParams -> FooResponse.
function responseTable(file) {
  const source = readFileSync(join(outDir, file), 'utf8');
  const entries = [];
  for (const match of source.matchAll(/"method": "([^"]+)",[^}]*?params\??: (\w+)/g)) {
    const [, method, paramsType] = match;
    entries.push({ method, responseType: findResponseType(paramsType) });
  }
  return entries;
}

function findResponseType(paramsType) {
  if (!paramsType.endsWith('Params')) return undefined;
  const name = paramsType.replace(/Params$/, 'Response');
  for (const dir of ['', 'v2']) {
    if (existsSync(join(outDir, dir, `${name}.ts`))) return { name, path: dir ? `./${dir}/${name}` : `./${name}` };
  }
  return undefined;
}

function renderInterface(interfaceName, entries) {
  const lines = entries.map(({ method, responseType }) => `  '${method}': ${responseType?.name ?? 'unknown'};`);
  return `export interface ${interfaceName} {\n${lines.join('\n')}\n}`;
}

function renderResponses(version, clientEntries, serverEntries) {
  const imports = new Map();
  for (const { responseType } of [...clientEntries, ...serverEntries]) {
    if (responseType) imports.set(responseType.name, responseType.path);
  }
  const importLines = [...imports]
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([name, path]) => `import type { ${name} } from '${path}';`);

  const header = `// Generated by scripts/generate.mjs from ${version}. Do not edit.`;
  return [
    header,
    importLines.join('\n'),
    renderInterface('ClientResponses', clientEntries),
    renderInterface('ServerRequestResponses', serverEntries),
    '',
  ].join('\n\n');
}

const version = run(['--version']);
rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });
run(['app-server', 'generate-ts', '--out', outDir]);

const clientEntries = responseTable('ClientRequest.ts');
const serverEntries = responseTable('ServerRequest.ts');
writeFileSync(join(outDir, 'responses.ts'), renderResponses(version, clientEntries, serverEntries));

const missing = [...clientEntries, ...serverEntries].filter((entry) => !entry.responseType).length;
console.log(
  `Generated ${clientEntries.length} client and ${serverEntries.length} server methods from ${version} (${missing} without a response type).`,
);
